### PR TITLE
#17 - migrate phpunit to kahlan

### LINKED ISSUE #17: Replace phpunit tests with Kahlan
We use [Kahlan](https://github.com/kahlan/kahlan) by default now, and it would be nice to migrate the tests in this repo so that developers only need to learn one testing library in detail.

### PR DESCRIPTION
**Pull request by patdel0**
Closes #17 
---
Seeing that we use Kahlan by default now, the PHPUnit tests have been rewritten.

### CODE REVIEW

**Comment by snim2** [comment]
So, there's one small thing that needs changing here, in `.github/workflows/continuous-integration.yml` this config:

```yaml
      - name: PHP unit tests
        run: vendor/bin/phpunit
```

Should now be:

```yaml
      - name: PHP unit tests
        run: vendor/bin/kahlan
```

or something similar. For that to work, your changes to `composer.json` and `composer.lock` will need to be cherry-picked into this branch.

@RobjS do you want to have a quick look at the tests themselves?

**Comment by snim2** [comment]
Also, it would be good to make a separate commit to remove `phpunit.xml`. 

In situations like this, it's sometimes helpful to use `git grep`, as in `git grep phpunit`, to help you see where random bits of config might still be lying around in the code.

**Comment by RobjS** [comment]
From first glance, the tests generally look good 🙂 . A couple of things I've noticed that might be worth fixing ahead of a closer code review:

* When I run `composer install` locally on this branch, it looks like I'm getting the following output:
   ```
   Installing dependencies from lock file (including require-dev)
   Verifying lock file contents can be installed on current platform.
   Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - psr/cache is locked to version 3.0.0 and an update of this package was not requested.
    - psr/cache 3.0.0 requires php >=8.0.0 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 2
    - psr/log is locked to version 2.0.0 and an update of this package was not requested.
    - psr/log 2.0.0 requires php >=8.0.0 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 3
    - symfony/deprecation-contracts is locked to version v3.2.0 and an update of this package was not requested.
    - symfony/deprecation-contracts v3.2.0 requires php >=8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 4
    - symfony/event-dispatcher-contracts is locked to version v3.2.0 and an update of this package was not requested.
    - symfony/event-dispatcher-contracts v3.2.0 requires php >=8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 5
    - symfony/service-contracts is locked to version v3.2.0 and an update of this package was not requested.
    - symfony/service-contracts v3.2.0 requires php >=8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 6
    - symfony/string is locked to version v6.2.2 and an update of this package was not requested.
    - symfony/string v6.2.2 requires php >=8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 7
    - psr/log 2.0.0 requires php >=8.0.0 -> your php version (7.4.33) does not satisfy that requirement.
    - composer/xdebug-handler 2.0.5 requires psr/log ^1 || ^2 || ^3 -> satisfiable by psr/log[2.0.0].
    - composer/xdebug-handler is locked to version 2.0.5 and an update of this package was not requested.
    ```
   @patdel0 It looks like you might be running PHP 8? If so, you'll probably want to use [PHP version](https://github.com/wilmoore/php-version) to switch to the latest patch of 7.4. If you've run the [dxw local env script](https://github.com/dxw/local-env/blob/main/Brewfile) you should already have PHP version installed.
* Is it intentional that this PR is from a fork rather than a branch within this repo? It'll probably be easier to see what's going on in the CI pipelines (and for any reviewer to pull the relevant branch locally) if it's a branch in this repo

**Comment by patdel0** [comment]
Thank you having a look at it.

I ran `php -v` and it returned the following:
```sh
PHP 7.4.33 (cli) (built: Dec  8 2022 21:24:25) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.33, Copyright (c), by Zend Technologies
```

It seems I was already running v7.4. I must have done something wrong when changing `composer.lock`.

Regarding working on a fork, it was intentional but with poor/bad reasoning:
I treated it as I would with other open source projects. 

Thanks for the heads up! I'll make sure to work on the repo from now on.

**Comment by snim2** [comment]
Hmm, so that installs for me locally with your latest commit, but not for GitHub actions...

**Comment by patdel0** [comment]
In `composer.json` I removed phpunit and added Kahlan. Any chance the Kahlan version might be causing an issue?

**Comment by snim2** [comment]
> In `composer.json` I removed phpunit and added Kahlan. Any chance the Kahlan version might be causing an issue?

If you look through the GitHub actions logs, it seems that `phpunit` is still in there?

**Comment by patdel0** [comment]
Yes, that's right.
I ran grep and it only mentions `phpunit` in `composer.lock`.

After looking into it for a bit, I found this:
https://github.com/10up/wp_mock/blob/trunk/composer.lock

We are using `10up/wp_mock`, which depends on `phpunit` to run.

I'll try and downgrade my php version to 7.2, see if I can replicate the GitHub actions logs issues.

**Comment by patdel0** [comment]
Downgrading to 7.2 didn't help

**Comment by snim2** [comment]
So, we want to stick to 7.4 because (for now) that's running on our servers. Are we still using that mocking library with Kahlan?

**Comment by patdel0** [comment]
Yes, it's being used in multiple tests.

**Comment by snim2** [comment]
> Yes, it's being used in multiple tests.

@RobjS do we have a preferred mocking library that we use with Kahlan?

**Comment by snim2** [comment]
@patdel0 so this is waiting on me to change the project settings before we merge this one (to remove the PHP 7.2 and 7.3 checks from branch protection) but the reason I haven't done that is so that we can get #20 merged first. Is that one ready for review?

**Pull request closed without merging**
