### PR TITLE
Add scripts to rule them all

### PR DESCRIPTION
**Pull request by patdel0**
These scripts were added to follow the Scripts to rule them all pattern:
https://github.com/github/scripts-to-rule-them-all

By standardising the names of our scripts, we can make it easier for contributors to understand how to make contributions to the project without needing to understand the inner workings of the project. This will allow maintainers to focus on managing the intricate details and ensure that the project runs smoothly.

### CODE REVIEW

**Comment by snim2** [comment]
@patdel0 let's remove the `composer.lock` file here and see if the pipeline passes. If it doesn't you could just put this up for review without that change.

**Comment by patdel0** [comment]
@snim2 The checks are still passing without `composer.lock`

**Comment by snim2** [comment]
@RobjS This looks OK to me, do you want to have a quick look at the `script/` dir before Patrick merges?

**Comment by RobjS** [comment]
I'm getting an error when running `script/run`:

```
==> Run all katas...
[Could not open file /Users/rob/Projects/patrick-iguana-theme/vendor/bin/kahlan]
[Failed to compile /Users/rob/Projects/patrick-iguana-theme/vendor/bin/kahlan, cannot run]
```

It looks like this is because Kahlan isn't required in the `composer.json`, so it isn't being installed when I run `script/setup`.

**Comment by snim2** [comment]
> I'm getting an error when running `script/run`:
> 
> ```
> ==> Run all katas...
> ...
> ```

And we should change any output that still refers to the katas BTW

**Comment by RobjS** [comment]
Yes, I think in this repo the unit test run can be incorporated in `script/test` (rather than separated out into `script/run`), because we are expecting those tests to pass, unlike with katas.

**Comment by patdel0** [comment]
@snim2 Changes were made to `composer.json`, should we still have `composer.lock` removed for the pipeline to pass?

**Comment by snim2** [comment]
@patdel0 I think at this point, you are safe to remove any old `7.2` and `7.3` configuration from the GitHub actions config, then see what happens!

**Comment by patdel0** [comment]
> @patdel0 I think at this point, you are safe to remove any old `7.2` and `7.3` configuration from the GitHub actions config, then see what happens!

Awesome! Thanks for confirming.

@RobjS @snim2 The PR is now ready for review again.

**Comment by snim2** [comment]
@patdel0 is this code not needed now?

**Pull request closed without merging**
