### PR TITLE
Chore/php8

### PR DESCRIPTION
**Pull request by RobjS**
This PR:

- Adds a CHANGELOG
- Removes support for PHP < 7.4, adds support for PHP > 8.1
- Implements standard dxw CS Config
- Upgrade to PHPUnit 9

### CODE REVIEW

**Review by snim2 — APPROVED** [review]
This looks fine, commit-wise. I tested it with `./vendor/bin/phpunit` and it seems OK, although there are a few deprecation warnings for PHP8.2.

**Comment by RobjS** [comment]
> This looks fine, commit-wise. I tested it with `./vendor/bin/phpunit` and it seems OK, although there are a few deprecation warnings for PHP8.2.

I can't see any when running locally, or in 8.2 on CI, do you have any more details?

**Comment by snim2** [comment]
> > This looks fine, commit-wise. I tested it with `./vendor/bin/phpunit` and it seems OK, although there are a few deprecation warnings for PHP8.2.
> 
> I can't see any when running locally, or in 8.2 on CI, do you have any more details?

So, this is what I'm seeing:

```bash
❯ rm -Rf vendor

❯ composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 65 installs, 0 updates, 0 removals
...

❯ php --version
PHP 8.2.8 (cli) (built: Jul  6 2023 10:57:44) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.8, Copyright (c), by Zend Technologies


PHP 8.2.8 (cli) (built: Jul  6 2023 10:57:44) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.8, Copyright (c), by Zend Technologies

❯ git branch
* chore/php8
  main

❯ ./vendor/bin/phpunit
PHPUnit 9.6.10 by Sebastian Bergmann and contributors.

...PHP Deprecated:  Creation of dynamic property LayoutRegister_Test::$expectedFunctions is deprecated in /Users/snim2/code/github.com/dxw/iguana-theme/src/Testing.php on line 9
PHP Deprecated:  Creation of dynamic property LayoutRegister_Test::$called is deprecated in /Users/snim2/code/github.com/dxw/iguana-theme/src/Testing.php on line 15
.
Deprecated: Creation of dynamic property LayoutRegister_Test::$expectedFunctions is deprecated in /Users/snim2/code/github.com/dxw/iguana-theme/src/Testing.php on line 9

Deprecated: Creation of dynamic property LayoutRegister_Test::$called is deprecated in /Users/snim2/code/github.com/dxw/iguana-theme/src/Testing.php on line 15
PHP Deprecated:  Creation of dynamic property LayoutRegister_Test::$expectedFunctions is deprecated in /Users/snim2/code/github.com/dxw/iguana-theme/src/Testing.php on line 9
PHP Deprecated:  Creation of dynamic property LayoutRegister_Test::$called is deprecated in /Users/snim2/code/github.com/dxw/iguana-theme/src/Testing.php on line 15
.
Deprecated: Creation of dynamic property LayoutRegister_Test::$expectedFunctions is deprecated in /Users/snim2/code/github.com/dxw/iguana-theme/src/Testing.php on line 9

Deprecated: Creation of dynamic property LayoutRegister_Test::$called is deprecated in /Users/snim2/code/github.com/dxw/iguana-theme/src/Testing.php on line 15
PHP Deprecated:  Creation of dynamic property LayoutRegister_Test::$expectedFunctions is deprecated in /Users/snim2/code/github.com/dxw/iguana-theme/src/Testing.php on line 9
PHP Deprecated:  Creation of dynamic property LayoutRegister_Test::$called is deprecated in /Users/snim2/code/github.com/dxw/iguana-theme/src/Testing.php on line 15
.
Deprecated: Creation of dynamic property LayoutRegister_Test::$expectedFunctions is deprecated in /Users/snim2/code/github.com/dxw/iguana-theme/src/Testing.php on line 9

Deprecated: Creation of dynamic property LayoutRegister_Test::$called is deprecated in /Users/snim2/code/github.com/dxw/iguana-theme/src/Testing.php on line 15
PHP Deprecated:  Creation of dynamic property Dxw\Iguana\Theme\Layout::$slug is deprecated in /Users/snim2/code/github.com/dxw/iguana-theme/src/Layout.php on line 18
PHP Deprecated:  Creation of dynamic property Dxw\Iguana\Theme\Layout::$templates is deprecated in /Users/snim2/code/github.com/dxw/iguana-theme/src/Layout.php on line 19
.
Deprecated: Creation of dynamic property Dxw\Iguana\Theme\Layout::$slug is deprecated in /Users/snim2/code/github.com/dxw/iguana-theme/src/Layout.php on line 18

Deprecated: Creation of dynamic property Dxw\Iguana\Theme\Layout::$templates is deprecated in /Users/snim2/code/github.com/dxw/iguana-theme/src/Layout.php on line 19
PHP Deprecated:  Creation of dynamic property Dxw\Iguana\Theme\Layout::$slug is deprecated in /Users/snim2/code/github.com/dxw/iguana-theme/src/Layout.php on line 18
PHP Deprecated:  Creation of dynamic property Dxw\Iguana\Theme\Layout::$templates is deprecated in /Users/snim2/code/github.com/dxw/iguana-theme/src/Layout.php on line 19
.
Deprecated: Creation of dynamic property Dxw\Iguana\Theme\Layout::$slug is deprecated in /Users/snim2/code/github.com/dxw/iguana-theme/src/Layout.php on line 18

Deprecated: Creation of dynamic property Dxw\Iguana\Theme\Layout::$templates is deprecated in /Users/snim2/code/github.com/dxw/iguana-theme/src/Layout.php on line 19
I                                                           9 / 9 (100%)

Time: 00:00.013, Memory: 8.00 MB

OK, but incomplete, skipped, or risky tests!
Tests: 9, Assertions: 14, Incomplete: 1.
```

**Comment by RobjS** [comment]
Sorry, I thought I'd switched to 8.2 locally when I hadn't! I see them now.

**Pull request merged**
